# Generated by Django 6.0.2 on 2026-03-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="is_markdown",
            field=models.BooleanField(default=True),
        ),
    ]
